name: Run Node.js API Tests in Docker

# Trigger workflow on push to main or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t api-test .

      # 4️⃣ Run Docker container
      - name: Run tests in Docker
        run: |
          mkdir -p $GITHUB_WORKSPACE/Report
          docker run -v $GITHUB_WORKSPACE/Report:/app/Report api-test

      # 5️⃣ Upload Reports
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: $GITHUB_WORKSPACE/Report