name: Run Node.js API Tests in Docker

# Trigger workflow on push to main or manually
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t api-test .

      # 4️⃣ Run Docker container
      - name: Run tests in Docker
        run: docker run -it api-test

      # 5️⃣ Optional: Save reports as artifacts
      - name: Upload reports
        uses: actions/upload-artifact@v3.2.2
        with:
          name: reports
          path: |
            Report/*.csv
            Report/*.txt
            Report/*.html
